<a href="https://colab.research.google.com/github/Loveline-Ezenwafor/Analysis-by-Loveline-Ezenwafor/blob/Analysis%2FPython-Programming/Project_3_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment

You will complete three tasks, each requiring you to write a function that performs a specific analysis on a provided dataset. Ensure your functions follow the provided format so they can be tested using an automated testing function.

In [1]:
import pandas as pd

import numpy as np

In [2]:
def create_sample_dataframe():
  """
  Creates a simple dataframe with three numerical columns and 10 rows.

  Returns:
    pandas.DataFrame: A dataframe with three columns named "col1", "col2", and "col3", each containing 10 random integers between 0 and 100.
  """
  np.random.seed(4)
  data = {
      "col1": np.random.randint(0, 100, 10),
      "col2": np.random.randint(0, 100, 10),
      "col3": np.random.randint(0, 100, 10),
  }
  return pd.DataFrame(data)

sample_df = create_sample_dataframe()
sample_df

   col1  col2  col3
0    46    55    55
1    55    55    21
2    69    57    21
3     1    36    73
4    87    50    38
5    72    44    56
6    50    38    66
7     9    52    46
8    58     3    30
9    94     0     8

In [3]:
#Random reviews
reviews = [
    "Great product! I love it!",
    "It's okay, but not what I expected.",
    "Very disappointed with this product.",
    "Excellent quality and value for money.",
    "I would not recommend this product.",
    "It's a good product, but a bit overpriced.",
    "I'm very satisfied with this purchase.",
    "It's a great product for the price.",
    "I'm not sure if I would buy it again.",
    "I'm very happy with this product.",
]


sample_df["reviews"] = reviews

# Print the dataframe
sample_df

   col1  col2  col3                                     reviews
0    46    55    55                   Great product! I love it!
1    55    55    21         It's okay, but not what I expected.
2    69    57    21        Very disappointed with this product.
3     1    36    73      Excellent quality and value for money.
4    87    50    38         I would not recommend this product.
5    72    44    56  It's a good product, but a bit overpriced.
6    50    38    66      I'm very satisfied with this purchase.
7     9    52    46         It's a great product for the price.
8    58     3    30       I'm not sure if I would buy it again.
9    94     0     8           I'm very happy with this product.

### Calculate Correlation:

Write a function to calculate the correlation between two variables in a dataset.

In [4]:
def calculate_correlation(df, col1, col2):
    """
    Calculate the correlation coefficient between two columns in a DataFrame.

    Parameters:
    df (DataFrame): The input DataFrame.
    col1 (str): The name of the first column.
    col2 (str): The name of the second column.

    Returns:
    float: The correlation coefficient.
    """
    # Your code here


    pass

In [5]:
# Simple test to check if code is correct
calculate_correlation(sample_df, "col1", "col2")
# Expected Output: -0.2657

### Calculate Skewness and Kurtosis:
Write a function to calculate the skewness and kurtosis of a variable in a dataset.

**Note: sklearn's skew and kurt function don't account for statistical bias. Prefer pandas functions.**

In [6]:
def calculate_skewness_kurtosis(df, col):
    """
    Calculate the skewness and kurtosis of a column in a DataFrame.

    Parameters:
    df (DataFrame): The input DataFrame.
    col (str): The name of the column.

    Returns:
    tuple: A tuple containing skewness and kurtosis.
    """
    # Your code here



    pass

In [15]:
import pandas as pd
from scipy.stats import skew, kurtosis

In [16]:
# Simple test to check if code is correct
skew_check, kurt_check = calculate_skewness_kurtosis(sample_df, "col1")
print(f"Skewness: {skew_check}, Kurtosis: {kurt_check}")
# Expected Output: Skewness: -0.6796, Kurtosis: -0.113

Skewness: -0.5731583417892245, Kurtosis: -0.6097627586074119

### Sentiment Analysis Summary:
Write a function to perform sentiment analysis on a dataset of text reviews and return the counts of positive, negative, and neutral reviews.

In [17]:
from textblob import TextBlob

def sentiment_analysis_summary(df, text_col):
    """
    Perform sentiment analysis on text data and return the counts of positive, negative, and neutral reviews.

    Parameters:
    df (DataFrame): The input DataFrame.
    text_col (str): The name of the column containing text data.

    Returns:
    dict: A dictionary with counts of positive, negative, and neutral reviews.
    """
    # Your code here



    pass

In [18]:
# Simple test to check if code is correct
sentiment_analysis_summary(sample_df, "reviews")
# Expected Output: {'positive': 7, 'negative': 2, 'neutral': 1}